---
title: "Assignments"
---

You will complete five assignments and three in-class quizzes. Each assignment is worth 10% of your final grade (50% in total), and the three quizzes together are worth the other 50%, or about 16.67% each.

Assignments are usually due on Wednesdays and Fridays at 11:59pm. You can submit them on Canvas (preferred) or by email (<danilo.freire@emory.edu>).

I encourage you to complete the assignments in Jupyter Notebooks and submit them as PDFs.

You will find the assignments in `.ipynb` format in the `assignments` folder of [the course repository](https://github.com/danilofreire/datasci151-summer/tree/main/assignments).

## Assignment timeline

| Sessions | Topics | Assignment | Submission Deadline |
|---------|-------|------------|---------------------|
| 02-03 | Variables and Lists | [Assignment 01](https://github.com/danilofreire/datasci151-summer/tree/main/assignments/01-assignment) | 2027-05-14 |
| 03-05 | Arrays and Conditional Statements| [Assignment 02](https://github.com/danilofreire/datasci151-summer/tree/main/assignments/02-assignment) | 2027-05-19 |
| 06-07 | While and For Loops, Functions| [Assignment 03](https://github.com/danilofreire/datasci151-summer/tree/main/assignments/03-assignment) | 2027-05-21 |
| 10-11 | Subsetting Data| [Assignment 04](https://github.com/danilofreire/datasci151-summer/tree/main/assignments/04-assignment) | 2027-05-26 |
| 12-13 | SQL | [Assignment 05](https://github.com/danilofreire/datasci151-summer/tree/main/assignments/05-assignment) | 2027-05-28 |

## In-class quizzes

We will have the quizzes in class on Fridays, and each one covers the material from the previous sessions. The quizzes are open-book and open-notes, but you cannot communicate with anyone during the quiz.

* Quiz 01: <https://github.com/danilofreire/datasci151-summer-quiz01>
* Quiz 02: <https://github.com/danilofreire/datasci151-summer-quiz02>
* Quiz 03: <https://github.com/danilofreire/datasci151-summer-quiz03>
