---
title: "Tutorials"
---

These tutorials show you how to install and use the tools we will use in class. Please work through them before our first class on 11 May, so you have everything ready when we start coding.

## Available tutorials

- [01 - VS Code and Anaconda tutorial](01-vscode-anaconda-tutorial.qmd)
- [02 - Jupyter Notebook and Markdown tutorial](02-jupyter-markdown-tutorial.qmd)
- [03 - Git and GitHub tutorial](03-github-tutorial.qmd)
- [04 - The terminal and conda environments tutorial](04-conda-environments-tutorial.qmd)
- [05 - SQLite and SQLite3 Editor tutorial](05-sqlite-tutorial.qmd) (please do this one before Lecture 11)

## Additional resources

### Further examples

- [testing-ipython.ipynb](testing-ipython.ipynb): a Jupyter Notebook with Markdown and code cells
- [testing-anaconda.py](testing-anaconda.py): a Python script to test your Anaconda installation

### Suggested books

All the books below are free online.

- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/README.html) by Allen Downey
- [Automate the Boring Stuff with Python](https://automatetheboringstuff.com) by Al Sweigart
- [Python for Everybody](https://www.py4e.com/book.php) by Charles Severance
- [Think Python](https://allendowney.github.io/ThinkPython/) by Allen Downey
- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
- [Select Star SQL](https://selectstarsql.com/) by Zi Chong Kao

### Online courses

The Coursera and edX courses are free if you choose the audit option.

- [Coursera: Python for Everybody Specialisation](https://www.coursera.org/specializations/python)
- [edX: Python Basics for Data Science](https://www.edx.org/learn/python/ibm-python-basics-for-data-science)
- [Software Carpentry: Plotting and Programming in Python](https://swcarpentry.github.io/python-novice-gapminder/)
- [Kaggle Learn: Intro to SQL](https://www.kaggle.com/learn/intro-to-sql)
- [Software Carpentry: Databases and SQL](https://swcarpentry.github.io/sql-novice-survey/)
- [Coursera: SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science)

### Documentation

- [Python Documentation](https://docs.python.org/3/)
- [pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [SQLite Documentation](https://www.sqlite.org/docs.html)
- [SQLBolt](https://sqlbolt.com/)
- [GitHub Docs](https://docs.github.com/en)

If you have any questions or problems with these tutorials, please [open a GitHub issue](https://github.com/danilofreire/datasci151-summer/issues), [submit a pull request](https://github.com/danilofreire/datasci151-summer/pulls) or [email me](mailto:danilo.freire@emory.edu).

I hope you find the tutorials useful! :)
